version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: latest
            python: latest #is it valid to have both of these here ??
        commands:
            - echo "Frontend - Installing dependencies..."
            - cd kyue-studio-website-v3
            - npm install
            - echo "Backend - Installing dependencies..."
            - cd ../kyue-studio-backend
            - pip install -r requirements.txt -t .
            # override pydantic with a lambda-compatible binary build
            - pip install --platform manylinux2014_aarch64 --target=./ --implementation cp --python-version 3.11 --only-binary=:all: --upgrade pydantic==2.8.2
            # - (cd dependencies; zip ../aws_lambda_artifact.zip -r .)
            - zip -r backend.zip .

    build:
        commands:
            - echo "Building Vite React app..."
            - cd ../kyue-studio-website-v3
            - npm run build
            
artifacts:
    files:
        - kyue-studio-website-v3/dist/**/*
        - kyue-studio-backend/backend.zip
        - cloudformation.yaml




