version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: latest
        commands:
            - echo "Installing dependencies..."
            - cd kyue-studio-website-v3
            - npm install

    build:
        commands:
            - echo "Building Vite React app..."
            - cd kyue-studio-website-v3
            - npm run build
            
artifacts:
    files:
        - '**/*'
    base-directory: dist

